# This file was generated by GoReleaser. DO NOT EDIT.
cask "gopin" do
  name "gopin"
  desc "Pin versions of go install commands for reproducible builds"
  homepage "https://github.com/nnnkkk7/gopin"
  version "1.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gopin"

  on_macos do
    on_intel do
      url "https://github.com/nnnkkk7/gopin/releases/download/v#{version}/gopin_#{version}_Darwin_x86_64.tar.gz"
      sha256 "33b744f4fbe966667cf18607003b102e634fcf3a14a54a33cc8175309b1192a7"
    end
    on_arm do
      url "https://github.com/nnnkkk7/gopin/releases/download/v#{version}/gopin_#{version}_Darwin_arm64.tar.gz"
      sha256 "f5663baeb6d6fe4a99803fedbf6b6de2a96a09aeef9e87737b3598e7d0b4156a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nnnkkk7/gopin/releases/download/v#{version}/gopin_#{version}_Linux_x86_64.tar.gz"
      sha256 "0fc95bcc2dfa47cc1deabcda3255a7964b10a8cf6737dd13c2fdcb771baa3eb8"
    end
    on_arm do
      url "https://github.com/nnnkkk7/gopin/releases/download/v#{version}/gopin_#{version}_Linux_arm64.tar.gz"
      sha256 "3cd03ef010a431636e3d44b48d710fc81628813657b41c4a28aab68fb3bceff1"
    end
  end

  # No zap stanza required
end
