# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-tidy" do
  name "mcp-tidy"
  desc "Visualize and manage MCP server usage in Claude Code"
  homepage "https://github.com/nnnkkk7/mcp-tidy"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-tidy"

  on_macos do
    on_intel do
      url "https://github.com/nnnkkk7/mcp-tidy/releases/download/v#{version}/mcp-tidy_#{version}_Darwin_x86_64.tar.gz"
      sha256 "68756011b7c1cef0f573ba73abacc446128b600098ebe58b36e5d2916f4a2a52"
    end
    on_arm do
      url "https://github.com/nnnkkk7/mcp-tidy/releases/download/v#{version}/mcp-tidy_#{version}_Darwin_arm64.tar.gz"
      sha256 "db49f22bcbc096e0b53cb1803cf9d6afc13c46d6970e0b26235737a3fa47bc91"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nnnkkk7/mcp-tidy/releases/download/v#{version}/mcp-tidy_#{version}_Linux_x86_64.tar.gz"
      sha256 "021a454f0c88e72f957419a6b755c54b6ec54d554dac00e49d10654b9e002a66"
    end
    on_arm do
      url "https://github.com/nnnkkk7/mcp-tidy/releases/download/v#{version}/mcp-tidy_#{version}_Linux_arm64.tar.gz"
      sha256 "972920b0f87742f8950c3166c4e5e0c2ca5b83d7700c5cf1160a4896979ecdac"
    end
  end

  # No zap stanza required
end
