# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-tidy" do
  name "mcp-tidy"
  desc "Visualize and manage MCP server usage in Claude Code"
  homepage "https://github.com/nnnkkk7/mcp-tidy"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-tidy"

  on_macos do
    on_intel do
      url "https://github.com/nnnkkk7/mcp-tidy/releases/download/v#{version}/mcp-tidy_#{version}_Darwin_x86_64.tar.gz"
      sha256 "985797b5da89b0bb68cabc521e7adbce3fbe24f74e0dbcb30ac478f1ee77f35d"
    end
    on_arm do
      url "https://github.com/nnnkkk7/mcp-tidy/releases/download/v#{version}/mcp-tidy_#{version}_Darwin_arm64.tar.gz"
      sha256 "76a6d0a0fb897747302fadedddcc4358cce75bb4a72b3f8c116439d3aa100c5b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nnnkkk7/mcp-tidy/releases/download/v#{version}/mcp-tidy_#{version}_Linux_x86_64.tar.gz"
      sha256 "0fa5f3e96ac5c6ddc3dbb81714032d026506f9cc3d3c09e79713c16524c48f85"
    end
    on_arm do
      url "https://github.com/nnnkkk7/mcp-tidy/releases/download/v#{version}/mcp-tidy_#{version}_Linux_arm64.tar.gz"
      sha256 "e8edfe28fc37a96366839145091baa1885588f24335a4c7198cca49bb9198a75"
    end
  end

  # No zap stanza required
end
