# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-tidy" do
  name "mcp-tidy"
  desc "Visualize and manage MCP server usage in Claude Code"
  homepage "https://github.com/nnnkkk7/mcp-tidy"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-tidy"

  on_macos do
    on_intel do
      url "https://github.com/nnnkkk7/mcp-tidy/releases/download/v#{version}/mcp-tidy_#{version}_Darwin_x86_64.tar.gz"
      sha256 "bf8ef70d8dd6472b01705d36942167bf896dbe62fa3c49fc3200ca2491742abc"
    end
    on_arm do
      url "https://github.com/nnnkkk7/mcp-tidy/releases/download/v#{version}/mcp-tidy_#{version}_Darwin_arm64.tar.gz"
      sha256 "f5a9d5216b0645f2580707af5371a3ebfa2964e512ef6b55d966c72b2e752335"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nnnkkk7/mcp-tidy/releases/download/v#{version}/mcp-tidy_#{version}_Linux_x86_64.tar.gz"
      sha256 "10c5e96c5186745d0a78af4fea07fe134795e69ccf01109eb4bf531a9cba0252"
    end
    on_arm do
      url "https://github.com/nnnkkk7/mcp-tidy/releases/download/v#{version}/mcp-tidy_#{version}_Linux_arm64.tar.gz"
      sha256 "eddecf72c19c607c291d089f8b88ca5c0dfb0620d84dc59216ea6efdee9857cb"
    end
  end

  # No zap stanza required
end
