# This file was generated by GoReleaser. DO NOT EDIT.
cask "memtui" do
  name "memtui"
  desc "A TUI to visualize and manage Memcached"
  homepage "https://github.com/nnnkkk7/memtui"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memtui"

  on_macos do
    on_intel do
      url "https://github.com/nnnkkk7/memtui/releases/download/v#{version}/memtui_#{version}_Darwin_x86_64.tar.gz"
      sha256 "c61dd705dd9f37799015d33eb32508fc3da8ad323ca0cc081a6577d8a64e2900"
    end
    on_arm do
      url "https://github.com/nnnkkk7/memtui/releases/download/v#{version}/memtui_#{version}_Darwin_arm64.tar.gz"
      sha256 "a7d9b4cb9f22fbc67ce554ed8c68d341fca43ccd35dc705dfd1ff9981c89c583"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nnnkkk7/memtui/releases/download/v#{version}/memtui_#{version}_Linux_x86_64.tar.gz"
      sha256 "f30a2dea4c2866a70ae661b9479a8e97cf6afe3798afc37b5652bd54df3880ca"
    end
    on_arm do
      url "https://github.com/nnnkkk7/memtui/releases/download/v#{version}/memtui_#{version}_Linux_arm64.tar.gz"
      sha256 "1df04c6f4b52531eaff694df0ac9df153b24fd6e86faf333540f84f950b4d996"
    end
  end

  # No zap stanza required
end
