# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyactions < Formula
  desc "A TUI to visualize and manage GitHub Actions"
  homepage "https://github.com/nnnkkk7/lazyactions"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nnnkkk7/lazyactions/releases/download/v0.0.9/lazyactions_0.0.9_Darwin_x86_64.tar.gz"
      sha256 "30abf785ef4e8da8f578011391af0f5fa8ccc703e157a6b89945edd80a081df9"

      def install
        bin.install "lazyactions"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nnnkkk7/lazyactions/releases/download/v0.0.9/lazyactions_0.0.9_Darwin_arm64.tar.gz"
      sha256 "b3b807c3489eef61b7155e675ea876fc77c09ea44d0c1ebb4e8904dc880ad74b"

      def install
        bin.install "lazyactions"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/lazyactions/releases/download/v0.0.9/lazyactions_0.0.9_Linux_x86_64.tar.gz"
      sha256 "a51885d0cc26e41c41db3f27bee9da3549734c64490a3b9b8a71a2639dc15aa6"
      def install
        bin.install "lazyactions"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/lazyactions/releases/download/v0.0.9/lazyactions_0.0.9_Linux_arm64.tar.gz"
      sha256 "5fffae24d231259716dd0c34d4c382eacbe6952940685cde424a071305ff4472"
      def install
        bin.install "lazyactions"
      end
    end
  end

  test do
    system "#{bin}/lazyactions", "--version"
  end
end
