# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyactions < Formula
  desc "A TUI to visualize and manage GitHub Actions"
  homepage "https://github.com/nnnkkk7/lazyactions"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nnnkkk7/lazyactions/releases/download/v0.0.1/lazyactions_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "c1eb0e4c0bfec57ca89e2069fe24600679494c1cf2b0281d501607f346bb650d"

      def install
        bin.install "lazyactions"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nnnkkk7/lazyactions/releases/download/v0.0.1/lazyactions_0.0.1_Darwin_arm64.tar.gz"
      sha256 "4e9c5c823a4af741b236a1b4ec39a240804644ad8027890853a6818228ee2cec"

      def install
        bin.install "lazyactions"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/lazyactions/releases/download/v0.0.1/lazyactions_0.0.1_Linux_x86_64.tar.gz"
      sha256 "d66133797453c71180170a67d1851bbbb923f0bcc1603cfe7b36dd04501cb9fb"
      def install
        bin.install "lazyactions"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/lazyactions/releases/download/v0.0.1/lazyactions_0.0.1_Linux_arm64.tar.gz"
      sha256 "946e8ca1c4b5f0cbcf4c9373e6ff6635ad756a7d89b03e20a779b1682dd61c28"
      def install
        bin.install "lazyactions"
      end
    end
  end

  test do
    system "#{bin}/lazyactions", "--version"
  end
end
