# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyactions < Formula
  desc "A TUI to visualize and manage GitHub Actions"
  homepage "https://github.com/nnnkkk7/lazyactions"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nnnkkk7/lazyactions/releases/download/v0.0.5/lazyactions_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "dee9cea09ed35b993b6f09eaf5b934ffcb29f976db6d5746b90841df54fa8b46"

      def install
        bin.install "lazyactions"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nnnkkk7/lazyactions/releases/download/v0.0.5/lazyactions_0.0.5_Darwin_arm64.tar.gz"
      sha256 "f558f2b51ae43c311b63bfa227435bf1604eb04b6de9fa4ce8d7b517d2c15021"

      def install
        bin.install "lazyactions"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/lazyactions/releases/download/v0.0.5/lazyactions_0.0.5_Linux_x86_64.tar.gz"
      sha256 "56acd47d2ac4f793af05b718addee88ac1bca8b7771928536dc9a4395b41a9fa"
      def install
        bin.install "lazyactions"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/lazyactions/releases/download/v0.0.5/lazyactions_0.0.5_Linux_arm64.tar.gz"
      sha256 "9f37544c1dc17714df7166a05d011531369ce6e04fa3196f7c844c6eead4c4bc"
      def install
        bin.install "lazyactions"
      end
    end
  end

  test do
    system "#{bin}/lazyactions", "--version"
  end
end
