# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memtui < Formula
  desc "A TUI to visualize and manage Memcached"
  homepage "https://github.com/nnnkkk7/memtui"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nnnkkk7/memtui/releases/download/v0.0.3/memtui_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "53ae1b58adaa95599f4c917389bcb20166cd7d4dd9dc7928e41780380149eb63"

      def install
        bin.install "memtui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nnnkkk7/memtui/releases/download/v0.0.3/memtui_0.0.3_Darwin_arm64.tar.gz"
      sha256 "5a54dee036b2434624f2e43548bdfd1570491c0c85229b65ac2fcb4b6030eb29"

      def install
        bin.install "memtui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/memtui/releases/download/v0.0.3/memtui_0.0.3_Linux_x86_64.tar.gz"
      sha256 "9c381498598bd1456b0dd01e709ec1d163c69ba398b5abeefe01e457f1da3069"
      def install
        bin.install "memtui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/memtui/releases/download/v0.0.3/memtui_0.0.3_Linux_arm64.tar.gz"
      sha256 "2a5ce77498f20cedacfafaa68a3c52bc5a28c10cfe56a11143570ff8d21c3109"
      def install
        bin.install "memtui"
      end
    end
  end

  test do
    system "#{bin}/memtui", "--version"
  end
end
