# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memtui < Formula
  desc "A TUI to visualize and manage Memcached"
  homepage "https://github.com/nnnkkk7/memtui"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nnnkkk7/memtui/releases/download/v0.0.6/memtui_0.0.6_Darwin_x86_64.tar.gz"
      sha256 "fd8819f8b8524cde76f5dca4057bee3578b8b956452a376f270e271d3945d170"

      def install
        bin.install "memtui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nnnkkk7/memtui/releases/download/v0.0.6/memtui_0.0.6_Darwin_arm64.tar.gz"
      sha256 "bf2c03a81794152b67aeafd6f6064f0e4df2a42c0bf4a9343795d9acce5c79d7"

      def install
        bin.install "memtui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/memtui/releases/download/v0.0.6/memtui_0.0.6_Linux_x86_64.tar.gz"
      sha256 "925a692394e046314937a2968e84c3ff62ed9b3700b66ac275df616a28f7b461"
      def install
        bin.install "memtui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/memtui/releases/download/v0.0.6/memtui_0.0.6_Linux_arm64.tar.gz"
      sha256 "e6af68a0035ed1458755686a86b4e5e79978215bff524a1e8029b293f7f6c6f3"
      def install
        bin.install "memtui"
      end
    end
  end

  test do
    system "#{bin}/memtui", "--version"
  end
end
