# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memtui < Formula
  desc "A TUI to visualize and manage Memcached"
  homepage "https://github.com/nnnkkk7/memtui"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nnnkkk7/memtui/releases/download/v0.0.4/memtui_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "682d10c6ae1d14991221f9d28eebcd26624d697f00e0d03773bec267e6a30c29"

      def install
        bin.install "memtui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nnnkkk7/memtui/releases/download/v0.0.4/memtui_0.0.4_Darwin_arm64.tar.gz"
      sha256 "d037481524b7b97ce8a94e14f3be190f7033be6340ab39c22317a964a8a934b0"

      def install
        bin.install "memtui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/memtui/releases/download/v0.0.4/memtui_0.0.4_Linux_x86_64.tar.gz"
      sha256 "e20f0c2b692a3b0670c0e84f7c98e85a75f7e03004b1a307d7bf8b9e1b3a5738"
      def install
        bin.install "memtui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/memtui/releases/download/v0.0.4/memtui_0.0.4_Linux_arm64.tar.gz"
      sha256 "0d3e530070205504373ec179e76384311ece6961ea311ed954980e87a5f5f945"
      def install
        bin.install "memtui"
      end
    end
  end

  test do
    system "#{bin}/memtui", "--version"
  end
end
