# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twain < Formula
  desc "A fast, lightweight static site generator for Cloudflare Pages"
  homepage "https://github.com/nnnkkk7/twain"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nnnkkk7/twain/releases/download/v0.1.1/twain_0.1.1_darwin_amd64.tar.gz"
      sha256 "12944e4e3628bca6f20374db08b859e10a34e162b784b89dd81eb85f191d8391"

      def install
        bin.install "twain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nnnkkk7/twain/releases/download/v0.1.1/twain_0.1.1_darwin_arm64.tar.gz"
      sha256 "4172540315b24e7713a216e288e577671d5a80ebfe1d2cce0656aeac49fc230a"

      def install
        bin.install "twain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/twain/releases/download/v0.1.1/twain_0.1.1_linux_amd64.tar.gz"
      sha256 "e88dfaa03e6117d6d71ce4ff23c95c7711d0cec56679ef7a6f7ccc8d34d88196"
      def install
        bin.install "twain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/twain/releases/download/v0.1.1/twain_0.1.1_linux_arm64.tar.gz"
      sha256 "b13aa300c722208a674985493040c22234b9109b771f2cc81321975ca5634b07"
      def install
        bin.install "twain"
      end
    end
  end

  test do
    system bin/"twain", "--version"
  end
end
