# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twain < Formula
  desc "A fast, lightweight static site generator for Cloudflare Pages"
  homepage "https://github.com/nnnkkk7/twain"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nnnkkk7/twain/releases/download/v0.1.0/twain_0.1.0_darwin_amd64.tar.gz"
      sha256 "7c1f5b697715005295179b03f6b8bc6c82d21e939ce5afe88f17230af9538008"

      def install
        bin.install "twain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nnnkkk7/twain/releases/download/v0.1.0/twain_0.1.0_darwin_arm64.tar.gz"
      sha256 "58b43733113e7327d31cf42f3795e239891aef52f286e7f400521a2e7950512c"

      def install
        bin.install "twain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/twain/releases/download/v0.1.0/twain_0.1.0_linux_amd64.tar.gz"
      sha256 "b23c1d23c66a75e00510c0ad5d7dd600480820cee89fd3c4fe351c5a99cfda5e"
      def install
        bin.install "twain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nnnkkk7/twain/releases/download/v0.1.0/twain_0.1.0_linux_arm64.tar.gz"
      sha256 "e03f07739452235680ddfdaa9e497a223a1736cd0f2cb6a1d80fba61501675a9"
      def install
        bin.install "twain"
      end
    end
  end

  test do
    system bin/"twain", "--version"
  end
end
